# Creating a Working Project Environment
# Step 1: Open VS Code on your computer. Create a new folder for your project that will hold all your files.
# Step 2: Navigate to the top left-hand corner of VS Code and click on "Terminal", then select "New Terminal" from the dropdown menu.
# Step 3: In the terminal that you have just created, type "git init" and hit enter. This will initialize a new Git repository in your project folder.
# Step 4: Before you begin coding and importing packages, it is important to create a virtual environment. In the terminal, type "python -m venv venv" and hit enter. When a new line appears in the terminal to write another command, the virtual environment has been created
# Step 5: Activate the virtual environment by typing "source venv/bin/activate" in the terminal and hitting enter (Note: This command only works for macOS and Linux). You will know you hav succeeded when "(venv)" appears at the beginning of the line in the terminal.
# Step 6: Create a file called .gitignore in the root of your project folder. This file should contain "venv/" so that the virtual environment does not appear in GitHub when you push your repository.
# Step 7: Install any packages you need for your project in the terminal using "pip install". For this example, I installed pandas by typing "pip install pandas" and hitting enter.
# Step 8: When all desired packages have been installed, create a requirements.txt file in the root of your project folder by typing "pip freeze > requirements.txt" in the terminal and pressing enter. This creates a list of all the packages in your virtual environment and their versions so someone can easily recreate your project.
# Step 9: Create new folders within your project to organize your files. Generally, you should include an "src" folder for source code, a "tests" folder for test files, and a "data" folder for datasets that you use.
# Step 10: Upload your datasets to the data folder, begin coding your project in the src folder, and write and run tests in the tests folder to ensure your code is functioning as intended.
# Step 11: Navigate to the "File" tab in the top left corner of VS Code and click "Save All" to ensure all your files are saved.
# Step 12: When you are done coding and have verified that your project is completely functional, push your project to Github by typing in the terminal: "git add .", then "git push origin main". If you need to go back and change something after pushing your project to Github, type "git pull origin main" into the terminal before the two commands previously listed. You can ensure that this was successful by looking under the "Source Control" tab on the left-hand side of VS Code. Ensure all of your changes are staged, then hit the "Commit" button.